### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by bkenn** [timrs2998/pdf-builder#14] opened 2017-07-24 21:32 UTC
Are there any plans to allow images? I cannot seem to find a function to add images.

**Comment by timrs2998** [comment] 2017-12-13 19:55
Sorry I haven't gotten back to you, I had notifications disabled for a while. Yes I think if I find some time to work on this project again, I'll be working on these issues I've laid out here. Otherwise feel free to submit a pull request or even fork the project for your uses. 

Duplicate of https://github.com/timrs2998/pdf-builder/issues/11

**Comment by timrs2998** [comment] 2019-04-26 13:01
resolved by https://github.com/timrs2998/pdf-builder/pull/17

**Closed by timrs2998** 2019-04-26 13:01 UTC
Labels: enhancement
